//! A CLI client for the notification API.

use eyre::Result;

use ntf_cli::NtfCli;

#[cfg_attr(
    test,
    expect(clippy::missing_panics_doc, reason = "code generated by tokio")
)]
#[tokio::main]
async fn main() -> Result<()> {
    color_eyre::install()?;
    NtfCli::run().await
}
